# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FastAwsVault < Formula
  desc "fav is a project designed to enhance your AWS connection experience. It's not here to replace aws-vault, but to work alongside it, making your connections faster and more efficient"
  homepage "https://canilho.net"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_darwin_amd64.zip"
      sha256 "a101b6c9f6c85c117d6b24ed19c50a5032bcda8c63e36fd158c3034a3532ab3b"

      def install
        bin.install "fav"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_darwin_arm64.zip"
      sha256 "2a2972f3b0024b2a4e75e9af906652304ffee9bc0933fa7e1921e0c8b18756ad"

      def install
        bin.install "fav"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_linux_amd64.zip"
      sha256 "1b75efd56300991d871d0602b0b881fad0e2ffcb5e50a8acc6bef0721df1df7f"

      def install
        bin.install "fav"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_linux_arm64.zip"
      sha256 "e2405cbf7b3c1e23df5af34dce3750a70c7fb794c7695aa2eea81c7828963b81"

      def install
        bin.install "fav"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_linux_arm.zip"
      sha256 "8a92461975310c9c9185d694bd7f93681b682864a01812426998e218ede0c470"

      def install
        bin.install "fav"
      end
    end
  end

  test do
    system "#{bin}/fav --help"
  end
end
