# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fav < Formula
  desc "fav is a project designed to enhance your AWS connection experience. It's not here to replace aws-vault, but to work alongside it, making your connections faster and more efficient"
  homepage "https://canilho.net"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_darwin_arm64.zip"
      sha256 "b9a939a63d276709719fa868e904a4f30230ae4afb10c28d6a1c9585d91fdb7e"

      def install
        bin.install "fav"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_darwin_amd64.zip"
      sha256 "e790c2f88e40b3db3df2d6c0194ad4f7f3056d70ab3a706bef45c37068e7bd88"

      def install
        bin.install "fav"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_linux_amd64.zip"
      sha256 "893b41b0cb58b1f872bd9c1452d4bce86dfc7629059340f4699f86fa794984fb"

      def install
        bin.install "fav"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_linux_arm.zip"
      sha256 "fd7b7ec10f9d964fee327bff380950353eecc5e404d3a986c52baeacdd83ab0d"

      def install
        bin.install "fav"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pcanilho/fast-aws-vault/releases/download/1.0.0/fast-aws-vault_1.0.0_linux_arm64.zip"
      sha256 "f5f0e28e33d0f3d4af0399995ffbb69363701b396737e1d055630fe32ed2472f"

      def install
        bin.install "fav"
      end
    end
  end

  test do
    system "#{bin}/fav --help"
  end
end
